name: Backport changes to maintenance branches
on:
 push:
  branches:
   - main
   - v/*
jobs:
  get-maintenance-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-maintenance-versions.outputs.versions }}
    steps:
      - id: get-maintenance-versions
        uses: hazelcast/hazelcast/.github/actions/get-supported-maintenance-versions

  backport-to-all-branch:
    needs: get-maintenance-versions
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.get-maintenance-versions.outputs.versions) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label-to-check-for: '["backport to all versions"]'
      target-branch: v/${{ matrix.version }}
    secrets: inherit

  backport-to-specified-branch:
    needs: get-maintenance-versions
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.get-maintenance-versions.outputs.versions) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label-to-check-for: '["backport to ${{ matrix.version }}"]'
      target-branch: v/${{ matrix.version }}
    secrets: inherit
