name: Backport changes to maintenance branches
on:
 push:
  branches:
   - main
   - v/*
jobs:
  get-maintenance-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-maintenance-versions.outputs.versions }}
    steps:
      - id: get-maintenance-versions
        uses: JackPGreen/hazelcast-tpm/.github/actions/get-supported-maintenance-versions@DI-349

  backport-to-specified-branch:
    runs-on: ubuntu-latest
    needs: get-maintenance-versions
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.get-maintenance-versions.outputs.versions) }}
    steps:
      - name: Get latest patch versions
        run: |
          echo ${{ matrix.version }}
