# This workflow will check if the incoming pull request includes any broken links

name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*']
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Check dead links
        uses: hazelcast/hazelcast-docs/.github/actions/validate@main

  # Ideally this would be a scheduled action to catch if a website *did* work, but subsequently went offline
  # But then it would have to notify *someone*, whereas a PR author notification is easier
  test-external-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-external-links
